import Footer from "./components/Footer";
import { TopAppBar } from "./components/TopAppBar";
import "./styles/globalStyles.scss";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <TopAppBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
